### ISSUE TITLE
Should ULOG_ENABLED be commented out?

### ISSUE THREAD

**Issue by forslund** [rdpoor/ulog#5]
The comments indicate that the `ULOG_ENABLED` define (at [ulog.hL84](https://github.com/rdpoor/ulog/blob/master/src/ulog.h#L84))

Is this the case or am I misunderstanding?

**Comment by rdpoor** [comment]
The comment preceding `#define ULOG_ENABLED` is poorly worded -- thank you for pointing that out.  I'll clean it up.

I should add that most people probably want `#define ULOG_ENALBED` un-commented by default, since they're probably planning on using the logging facility.   If they want to disable it, they can comment that line out.

**Comment by rdpoor** [comment]
Improved comment.
